### ISSUE TITLE
doesn't run 

### ISSUE THREAD

**Issue by hetSein** [lambdatwelve/plesk-cloudns#2]
Hi,
The description looks great and I would love to use the script, but I can't get it to work :(
Trying to use it on the recent Obsidian:

OS | ‪CloudLinux 7.7 (Valery Bykovsky)‬
Product | Plesk ObsidianVersion 18.0.21 Update #2

 placed the script in: /usr/local/psa/admin/plib/registry/EventListener
Edited with API credentials, but nothing happens

Created an alias for php: echo "alias php='/opt/plesk/php/7.3/bin/php'" >> ~/.bashrc
Still no luck
 Running the script manually gives an error:
PHP Fatal error:  Interface 'EventListener' not found in /usr/local/psa/admin/plib/registry/EventListener/ClouDNS.php on line 17

All help is appreciated :)

**Comment by hexblot** [comment]
Hello,
don't have an instance with Obsidian available to test on -- however according to the updated documentation, nothing should have changed. Are you sure that your ClouDNS quota is not met?

The error when manually running makes sense, since when running manually the interface "EventListener" (which is provided by Plesk) is not loaded. 

Please do the following to assist in finding a solution:
- I've hacked together an altered version of the file, which has a debug option. It's available at the following location:
https://raw.githubusercontent.com/lambdatwelve/plesk-cloudns/with-debug/ClouDNS.php 

Replace your current file with the above, and edit the `$debug = FALSE;` line to `$debug=TRUE;`.

Once done, monitor the Plesk log file at `/var/log/plesk/panel.log` file and try to add a domain.
You should see three messages, one saying that the hook was invoked, that is tried to add the zone, and the response from ClouDNS. 

Please post the relevant entries here. Thanks!

**Comment by hetSein** [comment]
Hi,

Thanks! The debug helps. Found out that I didn't had the IPv6 among the allowed ip's in ClouDNS api. 

But, I'm not there yet :(

Here is the log:

> 24-Nov-2019 22:32:32 Europe/Berlin] ClouDnsSlaveManager handle event hook called!
[2019-11-24 22:32:34.729] ERR [panel] [5ddaf6f28e7ca] Result of interface implementation call: failure: Could not find domain connect URL prefix for 2test.nl.
[24-Nov-2019 22:32:35 Europe/Berlin] ClouDnsSlaveManager handle event hook called!
[24-Nov-2019 22:32:35 Europe/Berlin] Attempting to add zone 2test.nl to the slaves
[24-Nov-2019 22:32:36 Europe/Berlin] Failed to create 2test.nl with message Invalid authentication, incorrect auth-id or auth-password.
[24-Nov-2019 22:32:36 Europe/Berlin] Array
(
    [status] => Failed
    [statusDescription] => Invalid IP address for the primary server.
)
[24-Nov-2019 22:32:36 Europe/Berlin] Failed to create 2test.nl with message Invalid IP address for the primary server.

**Comment by hetSein** [comment]
To make sure that isn't a authentication failure, I changed the authentication password and got this log outcome:

>     [statusDescription] => Invalid authentication, incorrect auth-id or auth-password.

> )

> [24-Nov-2019 22:39:16 Europe/Berlin] Failed to create 3test.nl with message Invalid authentication, incorrect auth-id or auth-password.

> [24-Nov-2019 22:39:16 Europe/Berlin] Failed to create 3test.nl with message Invalid authentication, incorrect auth-id or auth-password.
[24-Nov-2019 22:39:22 Europe/Berlin] ClouDnsSlaveManager handle event hook called!

**Comment by hetSein** [comment]
Got it :)
Edited the script variable $masterip with a IP value of teh plesk server, and it worked.
Thought it would find out on it's own, but needed some help (just like me ;)

Thanks for the help!
 
> 2019-11-24 22:44:03.223] ERR [panel] [5ddaf9a3090ac] Result of interface implementation call: failure: Could not find domain connect URL prefix for 4test.nl.
[24-Nov-2019 22:44:04 Europe/Berlin] ClouDnsSlaveManager handle event hook called!
[24-Nov-2019 22:44:04 Europe/Berlin] Attempting to add zone 4test.nl to the slaves
[24-Nov-2019 22:44:04 Europe/Berlin] Failed to create 4test.nl with message Invalid authentication, incorrect auth-id or auth-password.
[24-Nov-2019 22:44:04 Europe/Berlin] Array
(
    [status] => **Success**
    [statusDescription] => Domain zone 4test.nl was created successfully.
